version: '3.7'

services:
  
  consul-server:
    image: hashicorp/consul:1.11.1
    container_name: consul-server
    restart: always
    volumes:
     - ./server/server.json:/consul/config/server.json:ro
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent"

  consul-dashboard:
    #image: hashicorp/consul:1.9.6
    build:
      context: .
      dockerfile: ./dashboard/dashboard.Dockerfile
    container_name: consul-dashboard
    hostname: dashboard
    restart: always
    volumes:
     - ./dashboard/dashboard.json:/consul/config/dashboard.json:ro
     - ./intention-config-entry.json:/intention-config-entry.json
     - ./dashboard/go:/app
    networks:
      - consul
    ports:
      - "9002:9002"
    environment:
      #- PORT=9002
      - COUNTING_SERVICE_URL=http://localhost:5000
    command: "agent"

  consul-counting1:
    #image: hashicorp/consul:1.9.6
    build:
      context: .
      dockerfile: ./counting1/counting1.Dockerfile
    container_name: consul-counting1
    hostname: counting1
    restart: always
    volumes:
     - ./counting1/counting1.json:/consul/config/counting1.json:ro
     - ./counting1/go:/app
    networks:
      - consul
    ports:
      - "9003:9003"
    #environment:
      #- PORT=9003
    command: "agent"

  consul-counting2:
    #image: hashicorp/consul:1.9.6
    build:
      context: .
      dockerfile: ./counting2/counting2.Dockerfile
    container_name: consul-counting2
    hostname: counting2
    restart: always
    volumes:
     - ./counting2/counting2.json:/consul/config/counting2.json:ro
     - ./counting2/go:/app
    networks:
      - consul
    ports:
      - "9004:9004"
    #environment:
      #- PORT=9004
    command: "agent"
    
networks:
  consul:
    driver: bridge

